### ISSUE TITLE
 No CR3 found

### ISSUE THREAD

**Issue by Zero2A11** [ExaTrack/Kdrill#1]
```bash
Kdrill> python.exe .\Kdrill.py ..\memory\win10.raw -vv
  [!] CR3 is invalid, try fo foud a new CR3
  [!] CR3 not found :(
  [!] No CR3 found :-(
  [*] No CR3 set trying to find the a new CR3
  [!] CR3 not found :(
  [!] Shit, CR3 not found :-( Go to crawl CR3 in the wild !
#>>
```

My win10.raw was exported using winpmem_mini_x64_rc2 in the vmware virtual machine of win10

**Comment by Heurs** [comment]
Is it a full raw dump? No header like a crashdump image? I don't already support full raw dump, but It can be implemented (todo list added).

**Comment by Heurs** [comment]
Raw support added, is it good in your case (pushed in master)? (I tested with `winpmem_mini_x64_rc2`)
